# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 23:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', django_mysql.models.JSONField(default=dict, verbose_name='details')),
                ('extracted', models.DateTimeField(auto_now_add=True, verbose_name='Extraction datetime')),
                ('vk_id', models.IntegerField(verbose_name='id for owner')),
                ('vk_owner_id', models.IntegerField(verbose_name='owner id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'VK wall post',
                'verbose_name_plural': 'VK wall posts',
            },
        ),
    ]
